#!/bin/bash

export GITHUB_TOKEN=github_pat_CHANGEME
wget --quiet --wait 2 --random-wait https://download.lineageos.org/wade
awk 'BEGIN{
RS="</a>"
IGNORECASE=1
}
{
  for(o=1;o<=NF;o++){
    if ( $o ~ /href/){
      gsub(/.*href=\042/,"",$o)
      gsub(/\042.*/,"",$o)
      print $(o)
    }
  }
}' wade | grep mirrorbits | head -4 > list_of_wade

github-release  info --user ylvaj \
   --repo public \
   | grep artifact  > current_files_in_github

for i in `cat list_of_wade`
do
echo $i
echo "Downloading zip"
wget --quiet --wait 2 --random-wait $i
done

for i in `find . -type f \( -iname lineage\*m -o -iname lineage\*.zip -o -iname lineage\*img -o -iname lineage\*256 \) -printf '%f\n'`
do
rename -f 's/\?/./g' "${i}"
done

echo "Uploading "
for i in `find . -type f \( -iname lineage\*m -o -iname lineage\*.zip -o -iname lineage\*img -o -iname lineage\*256 \) -printf '%f\n'`
do
  if grep $i current_files_in_github > /dev/null
  then
    echo $i " exists in github"
    rm -f $i
  else
    echo $i " is a new file"
    github-release upload --user ylvaj \
          --repo public \
          --tag wade  \
          --file $i --name $i
    rm -fr $i
    sleep 1
  fi
done
