#!/bin/bash

new_dir=`date +%F`
DIRECTORY=/home/fsarchiver/"$new_dir"
#43200 is 12 hours
#10800 is 3 hours
upSeconds=`cat /proc/uptime`
upSeconds=${upSeconds%%.*}
   
if [ "${upSeconds}" -le 180 ]; then
  exit 0
fi 

lock_file="/tmp/cron_fsa.lock"
if [ -f $lock_file ] ; then
  #echo "Lockfile exists, aborting."
  exit 0
fi
touch $lock_file

mkdir $DIRECTORY
if [ ! -d "$DIRECTORY" ]; then
 # will enter here if $DIRECTORY doesn't exist.
    echo "ALERT cron.weekly.fsarchiver in $HOSTNAME failed" | mail -s "ALERT cron.weekly.fsarchiver in $HOSTNAME failed" root
 exit 0
fi

cd $DIRECTORY

##First backup GRUB-mbr
#dd if=/dev/sda of=mbr-backup bs=512 count=1
lsblk > LSBLK
tar zcf etc.tar.gz -C / etc

ROOT_PARTITION=`mount | grep -i "on / " | awk '{print $1}'`
NOW=`date +%H_%M_%S`
fsarchiver -A -s 700 -j1 savefs root.fsa $ROOT_PARTITION > /dev/null 2>&1

if [ $? -eq 0 ]; then
    #echo OK
    echo "SUCCESS cron.weekly.fsarchiver in $HOSTNAME success." | mail -s "SUCCESS cron.weekly.fsarchiver in $HOSTNAME success $NOW" root
else
    #echo FAIL
    echo "ALERT cron.weekly.fsarchiver in $HOSTNAME failed" | mail -s "ALERT cron.weekly.fsarchiver in $HOSTNAME failed $NOW" root
fi 

md5sum * > MD5SUMS
rm $lock_file

exit 0
